[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
MyModule = '0x1eae2f3589d1fc7ec9561c1fa7e57ce5e27e23fba4a7d40470f469f37f53c94b'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
